### ISSUE TITLE
syntax error in WORKSPACE file

### ISSUE THREAD

**Issue by Jiraphapa** [bark-simulator/bark#42] opened 2019-07-09 22:04 UTC
when calling `bazel run` command, the following ERROR messages are given

> ERROR: /path/to/WORKSPACE:22:1: syntax error at '<': expected expression
> ERROR: /path/to/WORKSPACE:29:1: non-keyword arg after keyword arg
> ERROR: error loading package 'external': Failed to parse WORKSPACE file
> ERROR: error loading package 'external': Failed to parse WORKSPACE file
> INFO: Elapsed time: 0.093s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (0 packages loaded)
> FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by Jiraphapa** [comment] 2019-07-09 22:05
adding `#sha1 = "8edc147d67ca85a93ed1f53628004528dc36a04d"` for pybind11 did solve the problem:

> http_archive(
>     name = "pybind11",
>     #sha1 = "8edc147d67ca85a93ed1f53628004528dc36a04d",
>     strip_prefix = "pybind11-2.3.0",
>     urls = ["https://github.com/pybind/pybind11/archive/v2.3.0.zip"],
>     build_file = "@//tools/pybind11:pybind.BUILD",
> )
>

**Comment by klemense1** [comment] 2019-07-11 14:40
This seems odd, as #sha1 is just a commend. I would assume that it should not change anything to add such a line. Also, the problem does not occur on the ci and under linux. You're os is mac, right?

**Comment by Jiraphapa** [comment] 2019-07-11 14:42
yes, it's macOS 10.14.5

**Comment by klemense1** [comment] 2019-07-11 14:44
Alright, I will try it out again to reproduce it.

**Comment by klemense1** [comment] 2019-07-13 15:20
I could not reproduce the issue, thus I am going to close it for now.

**Closed by klemense1** 2019-07-13 15:20 UTC
